### ISSUE TITLE
How can I get the English version of this tutorial?

### ISSUE THREAD

**Issue by Harrypotterrrr** [zergtant/pytorch-handbook#6]
could you tell me the English version of ipynb, I would like to read both, thx!~

**Comment by zergtant** [comment]
sorry
The current plan is to complete this tutorial in this March.
and then may be it will translate to English.
But I am not sure if the English version will be very rigorous or not.Because there are many terminology  that need to be confirmed.

After the tutorial  completed, let’s see what follow-up plans are there.

thanks
